// USER TYPES
export const CREATE_USER = 'CREATE_USER';
export const SET_CREATE_USER_ALERT_MESSAGE = 'SET_CREATE_USER_ALERT_MESSAGE';
export const SET_CREATE_USER_ALERT_VISIBILITY = 'SET_CREATE_USER_ALERT_VISIBILITY';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const RESET_ALERT = 'RESET_ALERT';

// SUDOKU TYPES
export const GET_SUDOKUS = 'GET_SUDOKUS';
export const SET_CURRENT_SUDOKU = 'SET_CURRENT_SUDOKU';
export const RESET_CURRENT_SUDOKU = 'RESET_CURRENT_SUDOKU';
export const SET_BOARD_STATE = 'SET_BOARD_STATE';
export const SET_BOARD_STATE_TO_INITIAL_BOARD = 'SET_BOARD_STATE_TO_INITIAL_BOARD';
export const ADD_ERROR = 'ADD_ERROR';
export const RESET_ERRORS = 'RESET_ERRORS';