export const CREATE_USER = 'CREATE_USER';
export const SET_CREATE_USER_ALERT_MESSAGE = 'SET_CREATE_USER_ALERT_MESSAGE';
export const SET_CREATE_USER_ALERT_VISIBILITY = 'SET_CREATE_USER_ALERT_VISIBILITY';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const RESET_ALERT = 'RESET_ALERT';